teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 0.75
      y: 0.25
    #scale_linear_turbo:
   #   x: 1.5

    axis_angular:  
      yaw: 3
    scale_angular:
      yaw: .75

    require_enable_button: false  
    #enable_turbo_button: 5 

# 1 is left joy stick vertical
# 0 is left joy stick horizontal
# 3 is right joy stick horizontal